site_name: ICDAR 2021 Competition on Historical Map Segmentation
repo_url: https://github.com/icdar21-mapseg/icdar21-mapseg.github.io
site_description: Official site for the ICDAR 2021 Competition on Historical Map Segmentation. Download all material and review score boards here.
site_author: J. Chazalon; E. Carlinet; Y. Chen; J. Perret; C. Mallet; B. Dum√©nieu; T. G√©raud
theme:
    name: readthedocs
    # collapse_navigation: true
    custom_dir: theme_customizations
edit_uri: edit/main/docs/
nav:
  - index.md
  - Tasks:
    - tasks/task1.md
    - tasks/task2.md
    - tasks/task3.md
  - Resources:
    - downloads.md
    - 'üèÜ Score board': score_board.md
    # - registration.md
    # - rules.md
  - More information:
    - contact.md
    # - 'Issue Tracker (external)': 'https://github.com/icdar21-mapseg/icdar21-mapseg.github.io/issues'
    - 'Twitter (external)': 'https://twitter.com/ICDAR21_MapSeg'
markdown_extensions:
  - markdown_katex:
      no_inline_svg: True
      insert_fonts_css: True
      # macro-file: macros.tex
  - attr_list
  - fontawesome_markdown
strict: true
# new analytics
google_analytics: ['G-HSMK67B4JN', 'icdar21-mapseg.github.io']